### ISSUE TITLE
This syntax error is protecting against a logic error

### ISSUE THREAD

**Issue by ljharb** [jugglinmike/proposal-conflict-comment#1]
In your example:
```js
function onRequest() {
<<<<<<< HEAD
  var screen = document.querySelector('.screen7');
=======
  var screen = document.getElementsByClassName('screen8')[0];
>>>>>>> refactor-overlay
```

By treating the conflict markers as comments, `screen` will silently be set to screen 8, instead of 7 - this could cause a much harder to triage production bug if the wrong screen got updated - perhaps because the logic below (that uses `screen`) did *not* conflict, and assumes screen 7.

**Comment by bathos** [comment]
Indeed, I don’t understand the rationale in the readme. In the event that code is somehow deployed with merge markers, the last thing I would want would be for it to be (potentially) successfully executable ... with unknown behavior.

**Comment by rkirsling** [comment]
Let's not forget what day it is. 😅

**Comment by bathos** [comment]
haha. it didn’t occur to me at all ... given this is more believable/coherent than many earnestly proposed things on e.g. esdiscuss, I think I’d readily fall for it again, too.

**Comment by rkirsling** [comment]
I did too, until I shared it with somebody who replied, "oh, I wanted to write an April Fool's proposal too!"

**Comment by ljharb** [comment]
¯\\\_(ツ)_/¯ on the off chance it's serious, the point had to be made, and general opinion has been that april fool's day is supposed to be cancelled during covid-19 due to being in poor taste, so i thought it was better to be safe than sorry :-)

**Comment by fChristenson** [comment]
I had to reread the proposal a few times to make sure I understood everything correctly. It has to be a joke.

**Comment by ljharb** [comment]
Closing per https://github.com/jugglinmike/proposal-conflict-comment/commit/81f8d9c05148a74875b3b704f0c614ecba83652f
