### ISSUE TITLE
Asking to modify a language to fix an user issue ???

### ISSUE THREAD

**Issue by lifaon74** [jugglinmike/proposal-conflict-comment#3]
Seems completely **overkill** to me. You're asking to modify a language used by millions of people just to support mistakes done by a **really really few people** which doesn't know how to properly use a tool...

In a real dev environment (company business) this **never ever** append => tests, ci checking/building code, lint, version control, etc... Moreover, github warns you about this, and of course you create branches and doesn't push on master... So typically, your example should absolutely **never append**, except for extreme amateurs

**Comment by ljharb** [comment]
This was likely an April Fool’s joke, see https://github.com/jugglinmike/proposal-conflict-comment/issues/1#issuecomment-607424905

**Comment by jugglinmike** [comment]
The joke's run it's course by now. I've amended the readme and the draft specification page to avoid further confusion.
